<a href="https://colab.research.google.com/github/danielpy108/PytorchTutorial/blob/master/00_Playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Playground

This playground is meant to be for playing with the pytorch framework.

In [0]:
import torch
import numpy as np

In [23]:
# Creating tensors
t0 = torch.tensor(1)
t1 = torch.tensor([1, 2, 3, 4, 5, 6])
t2 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t3 = torch.tensor([[[1, 2], [3, 4], [5, 6]]])

print(f"Scalar:")
print(t0)
print(f"shape:\t {t0.shape}")
print(f"size:\t {t0.size()}")
print(f"dim:\t {t0.dim()}\n")

print(f"Vector:")
print(t1)
print(f"shape:\t {t1.shape}")
print(f"size:\t {t1.size()}")
print(f"dim:\t {t1.dim()}\n")

print(f"Matrix:")
print(t2)
print(f"shape:\t {t2.shape}")
print(f"size:\t {t2.size()}")
print(f"dim:\t {t2.dim()}\n")

print(f"Tensor:")
print(t3)
print(f"shape:\t {t3.shape}")
print(f"size:\t {t3.size()}")
print(f"dim:\t {t3.dim()}\n")

Scalar:
tensor(1)
shape:	 torch.Size([])
size:	 torch.Size([])
dim:	 0

Vector:
tensor([1, 2, 3, 4, 5, 6])
shape:	 torch.Size([6])
size:	 torch.Size([6])
dim:	 1

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
shape:	 torch.Size([2, 3])
size:	 torch.Size([2, 3])
dim:	 2

Tensor:
tensor([[[1, 2],
         [3, 4],
         [5, 6]]])
shape:	 torch.Size([1, 3, 2])
size:	 torch.Size([1, 3, 2])
dim:	 3



In [87]:
# Creating more tensors

array = np.random.rand(1, 5)

print(f"{torch.from_numpy(array)}\n")
print(f"{torch.rand(size=(3,3), dtype=torch.float64)}\n")
print(f"{torch.randn(size=(3,3), dtype=torch.double)}\n")
print(f"{torch.randint(low=-5, high=5, size=(2, 3, 2))}\n")
print(f"{torch.arange(start=-3, end=1, step=0.5)}\n")
print(f"{torch.ones(size=(1, 4), dtype=torch.int8)}\n")
print(f"{torch.zeros(size=(1, 4), dtype=torch.float)}\n")
print(f"{torch.full(size=(3,3), fill_value=-1, dtype=torch.float)}\n")
print(f"{torch.randperm(10)}")

tensor([[0.0504, 0.5402, 0.0542, 0.9279, 0.8893]], dtype=torch.float64)

tensor([[0.0627, 0.8861, 0.8400],
        [0.5174, 0.6791, 0.1740],
        [0.8459, 0.8922, 0.3019]], dtype=torch.float64)

tensor([[ 0.1674,  1.2729,  0.4745],
        [-1.1291,  0.7985, -0.2379],
        [-0.7141,  0.6781,  1.3394]], dtype=torch.float64)

tensor([[[-3,  0],
         [-2,  2],
         [-4, -2]],

        [[ 4, -4],
         [ 4, -3],
         [ 3,  3]]])

tensor([-3.0000, -2.5000, -2.0000, -1.5000, -1.0000, -0.5000,  0.0000,  0.5000])

tensor([[1, 1, 1, 1]], dtype=torch.int8)

tensor([[0., 0., 0., 0.]])

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])

tensor([1, 8, 4, 3, 9, 0, 2, 7, 5, 6])


In [73]:
# Tensor rezising
print(f"Original tensor:\t {t1}\n")
print("Reshape 1: to matrix")
print(f"{t1.reshape(2,3)}\n")
print("Reshape 2: to tensor")
print(f"{t1.reshape(2, 1, 3)}\n")
print("Reshape 3: add one dimenssion")
print(f"{t1.reshape(1, -1)}\n")
print("Reshape 4: turn to column vector")
print(f"{t1.reshape(-1, 1)}\n")

Original tensor:	 tensor([1, 2, 3, 4, 5, 6])

Reshape 1: to matrix
tensor([[1, 2, 3],
        [4, 5, 6]])

Reshape 2: to tensor
tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

Reshape 3: add one dimenssion
tensor([[1, 2, 3, 4, 5, 6]])

Reshape 4: turn to column vector
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])



In [80]:
# Tensor rezising
print(f"Original tensor:\n{t2}\n")
print("Reshape 1: collapse dim")
print(f"{t2.reshape(1, -1)}\n")
print("Reshape 2: to column vector")
print(f"{t2.reshape(-1, 1)}\n")
print("Reshape 3: to row vector")
print(f"{t2.reshape(-1, 1).T[0]}\n")
print("Reshape 4: to row vector")
print(f"{t2.reshape(-1, 1).T[0]}\n")

print("Squeeze")
print(f"{torch.squeeze(t2, dim=0)}\n")
print(f"{torch.squeeze(t2, dim=-1)}\n")

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Reshape 1: collapse dim
tensor([[1, 2, 3, 4, 5, 6]])

Reshape 2: to column vector
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

Reshape 3: to row vector
tensor([1, 2, 3, 4, 5, 6])

Reshape 4: to row vector
tensor([1, 2, 3, 4, 5, 6])

Squeeze
tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

